spring.application.name=PELICULAS
spring.datasource.url=jdbc:postgresql://localhost:5432/practica5_db
spring.datasource.username=postgres
spring.datasource.password=loverain
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
